version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile-local-dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/public
      - /usr/src/app/vendors
    ports:
      - "3000:3000"
