v: 2.6.0
overrideConfig: q
ie:
    - DS_Store
    - less
    - scss
id:
    - scss
    - .svn
    - .sass-cache
cleanPublic: 'true'
patternStates:
    - inprogress
    - inreview
    - complete
cacheBusterOn: 'true'
exportDir: export
publicDir: public
sourceDir: source
defaultPattern: all
defaultShowPatternInfo: false
plugins:
    reload:
        enabled: true
    dataInheritance:
        enabled: true
ishMinimum: '320'
ishMaximum: '1920'
ishControlsHide:
    - hay
    - disco
    - random
ishViewportRange:
    s:
        - 352
        - 352
    m:
        - 800
        - 800
    l:
        - 992
        - 992
lineageMatch: '{{>([ ]+)?([A-Za-z0-9-_]+)(?:\:[A-Za-z0-9-]+)?(?:(| )\(.*)?([ ]+)?}}'
lineageMatchKey: 2
patternExtension: mustache
mustacheHelperExt: helper.php
styleguideKit: pattern-lab/styleguidekit-mustache-default
styleguideKitPath: vendor/pattern-lab/styleguidekit-mustache-default
